BADGE_CATALOG = [
    {
        "code": "first_fortune",
        "name": "初来乍到",
        "category": "fortune",
        "description": "首次查看当日运势",
        "sort_order": 1,
        "levels": [
            {"level": 1, "title": "初访之舟", "condition_type": "first_time", "metric_key": "fortune_exists", "threshold": 1, "description": "首次查看当日运势"},
        ],
    },
    {
        "code": "diary_writer",
        "name": "心灵笔触",
        "category": "diary",
        "description": "记录情绪日记天数",
        "sort_order": 2,
        "levels": [
            {"level": 1, "title": "萌生笔意", "condition_type": "count", "metric_key": "diary_days", "threshold": 3, "description": "记录情绪日记满 3 天"},
            {"level": 2, "title": "信笺常客", "condition_type": "count", "metric_key": "diary_days", "threshold": 7, "description": "记录情绪日记满 7 天"},
            {"level": 3, "title": "心语成章", "condition_type": "count", "metric_key": "diary_days", "threshold": 15, "description": "记录情绪日记满 15 天"},
            {"level": 4, "title": "心迹长存", "condition_type": "count", "metric_key": "diary_days", "threshold": 30, "description": "记录情绪日记满 30 天"},
        ],
    },
    {
        "code": "answer_traveler",
        "name": "解惑旅人",
        "category": "answer",
        "description": "使用答案之书累计次数",
        "sort_order": 3,
        "levels": [
            {"level": 1, "title": "迷途寻问", "condition_type": "count", "metric_key": "answer_count", "threshold": 10, "description": "使用答案之书累计 10 次"},
            {"level": 2, "title": "解惑学徒", "condition_type": "count", "metric_key": "answer_count", "threshold": 50, "description": "使用答案之书累计 50 次"},
            {"level": 3, "title": "明灯行者", "condition_type": "count", "metric_key": "answer_count", "threshold": 200, "description": "使用答案之书累计 200 次"},
            {"level": 4, "title": "智慧先知", "condition_type": "count", "metric_key": "answer_count", "threshold": 1000, "description": "使用答案之书累计 1000 次"},
        ],
    },
    {
        "code": "lucky_streak",
        "name": "好运连莲",
        "category": "fortune",
        "description": "连续多天获得高分运势",
        "sort_order": 4,
        "levels": [
            {"level": 1, "title": "祥瑞之始", "condition_type": "streak", "metric_key": "lucky_fortune_streak", "threshold": 3, "description": "连续 3 天运势评级为上上签或更高"},
            {"level": 2, "title": "鸿运当头", "condition_type": "streak", "metric_key": "lucky_fortune_streak", "threshold": 7, "description": "连续 7 天运势评级为上上签或更高"},
        ],
    },
    {
        "code": "login_streak",
        "name": "恒心之岛",
        "category": "login",
        "description": "连续登录天数",
        "sort_order": 5,
        "levels": [
            {"level": 1, "title": "七日驻留", "condition_type": "streak", "metric_key": "login_streak", "threshold": 7, "description": "连续登录 7 天"},
            {"level": 2, "title": "潮汐守望", "condition_type": "streak", "metric_key": "login_streak", "threshold": 30, "description": "连续登录 30 天"},
            {"level": 3, "title": "季风航标", "condition_type": "streak", "metric_key": "login_streak", "threshold": 100, "description": "连续登录 100 天"},
            {"level": 4, "title": "永恒灯塔", "condition_type": "streak", "metric_key": "login_streak", "threshold": 365, "description": "连续登录 365 天"},
        ],
    },
    {
        "code": "share_station",
        "name": "心卡驿站",
        "category": "plaza",
        "description": "成功分享运势或答案卡片",
        "sort_order": 6,
        "levels": [
            {"level": 1, "title": "见习驿员", "condition_type": "count", "metric_key": "plaza_card_count", "threshold": 1, "description": "成功分享运势/答案卡片 1 次"},
            {"level": 2, "title": "正式驿员", "condition_type": "count", "metric_key": "plaza_card_count", "threshold": 10, "description": "累计分享 10 次"},
            {"level": 3, "title": "卡片信使", "condition_type": "count", "metric_key": "plaza_card_count", "threshold": 50, "description": "累计分享 50 次"},
            {"level": 4, "title": "驿站之主", "condition_type": "count", "metric_key": "plaza_card_count", "threshold": 200, "description": "累计分享 200 次"},
        ],
    },
    {
        "code": "favorite_collector",
        "name": "收藏小栈",
        "category": "favorite",
        "description": "收藏内容累计数量",
        "sort_order": 7,
        "levels": [
            {"level": 1, "title": "拾贝新手", "condition_type": "count", "metric_key": "favorite_count", "threshold": 3, "description": "收藏内容累计 3 条"},
            {"level": 2, "title": "珍藏小栈", "condition_type": "count", "metric_key": "favorite_count", "threshold": 15, "description": "收藏内容累计 15 条"},
            {"level": 3, "title": "鉴赏大师", "condition_type": "count", "metric_key": "favorite_count", "threshold": 50, "description": "收藏内容累计 50 条"},
            {"level": 4, "title": "时空收藏家", "condition_type": "count", "metric_key": "favorite_count", "threshold": 200, "description": "收藏内容累计 200 条"},
        ],
    },
    {
        "code": "social_master",
        "name": "社交达人",
        "category": "plaza",
        "description": "在分享广场发表评论或点赞",
        "sort_order": 8,
        "levels": [
            {"level": 1, "title": "初次登门", "condition_type": "count", "metric_key": "plaza_interaction_count", "threshold": 3, "description": "在分享广场发表评论或点赞 3 次"},
            {"level": 2, "title": "串门熟手", "condition_type": "count", "metric_key": "plaza_interaction_count", "threshold": 50, "description": "互动累计 50 次"},
            {"level": 3, "title": "群岛访客", "condition_type": "count", "metric_key": "plaza_interaction_count", "threshold": 200, "description": "互动累计 200 次"},
            {"level": 4, "title": "知交满岛", "condition_type": "count", "metric_key": "plaza_interaction_count", "threshold": 800, "description": "互动累计 800 次"},
        ],
    },
    {
        "code": "fortune_companion",
        "name": "签运随身",
        "category": "fortune",
        "description": "累计查看运势天数",
        "sort_order": 9,
        "levels": [
            {"level": 1, "title": "一签启运", "condition_type": "count", "metric_key": "fortune_days", "threshold": 7, "description": "累计查看运势 7 天"},
            {"level": 2, "title": "签途常客", "condition_type": "count", "metric_key": "fortune_days", "threshold": 30, "description": "累计查看运势 30 天"},
            {"level": 3, "title": "签缘行者", "condition_type": "count", "metric_key": "fortune_days", "threshold": 100, "description": "累计查看运势 100 天"},
            {"level": 4, "title": "灵签居士", "condition_type": "count", "metric_key": "fortune_days", "threshold": 300, "description": "累计查看运势 300 天"},
        ],
    },
]
