"""alter password_hash length

Revision ID: 25f728fbc316
Revises: 31b42a074bc7
Create Date: 2026-05-03 12:35:51.833817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25f728fbc316'
down_revision = '31b42a074bc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mood_analysis_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trigger_event', sa.String(length=32), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('result_text', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    with op.batch_alter_table('mood_analysis_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mood_analysis_jobs_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mood_analysis_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_mood_analysis_jobs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_comment='密码哈希（bcrypt）',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_comment='密码哈希（bcrypt）',
               existing_nullable=True)

    with op.batch_alter_table('mood_analysis_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mood_analysis_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_mood_analysis_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_mood_analysis_jobs_next_run_at'))

    op.drop_table('mood_analysis_jobs')
    # ### end Alembic commands ###
