"""Initial migration

Revision ID: 31b42a074bc7
Revises: 
Create Date: 2026-04-25 16:14:47.005191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '31b42a074bc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary_entries', schema=None) as batch_op:
        batch_op.alter_column('mood_tag',
               existing_type=postgresql.ENUM('HAPPY', 'CALM', 'SAD', 'ANGRY', 'TIRED', name='moodtype'),
               comment=None,
               existing_comment='情绪标签',
               existing_nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=2000),
               comment=None,
               existing_comment='日记内容，1-2000字符',
               existing_nullable=False)
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否公开，默认false',
               existing_nullable=False)
        batch_op.alter_column('created_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='创建日期（冗余字段，便于按日期查询）',
               existing_nullable=False)

    with op.batch_alter_table('plaza_cards', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=postgresql.ENUM('FORTUNE', 'ANSWER', name='cardtype'),
               comment=None,
               existing_comment='卡片类型：fortune|answer',
               existing_nullable=False)
        batch_op.alter_column('snapshot_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='分享卡片图片URL',
               existing_nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='分享文案，1-100字符',
               existing_nullable=True)
        batch_op.alter_column('tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=10)),
               comment=None,
               existing_comment='标签数组，最多3个，每个1-10字符',
               existing_nullable=True)
        batch_op.alter_column('likes_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='点赞数缓存',
               existing_nullable=False)
        batch_op.drop_column('source_id')

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('mood_tendency',
               existing_type=postgresql.ENUM('OPTIMISTIC', 'CALM', 'ANXIOUS', name='moodtendency'),
               type_=sa.String(length=50),
               comment='情绪倾向，AI分析生成，例如"optimistic"/"anxious"等',
               existing_comment='情绪倾向：optimistic/calm/anxious',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('mood_tendency',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('OPTIMISTIC', 'CALM', 'ANXIOUS', name='moodtendency'),
               comment='情绪倾向：optimistic/calm/anxious',
               existing_comment='情绪倾向，AI分析生成，例如"optimistic"/"anxious"等',
               existing_nullable=True)

    with op.batch_alter_table('plaza_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='源记录ID（运势ID或答案ID）'))
        batch_op.alter_column('likes_count',
               existing_type=sa.INTEGER(),
               comment='点赞数缓存',
               existing_nullable=False)
        batch_op.alter_column('tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=10)),
               comment='标签数组，最多3个，每个1-10字符',
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=100),
               comment='分享文案，1-100字符',
               existing_nullable=True)
        batch_op.alter_column('snapshot_url',
               existing_type=sa.VARCHAR(length=500),
               comment='分享卡片图片URL',
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=postgresql.ENUM('FORTUNE', 'ANSWER', name='cardtype'),
               comment='卡片类型：fortune|answer',
               existing_nullable=False)

    with op.batch_alter_table('diary_entries', schema=None) as batch_op:
        batch_op.alter_column('created_date',
               existing_type=sa.DATE(),
               comment='创建日期（冗余字段，便于按日期查询）',
               existing_nullable=False)
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               comment='是否公开，默认false',
               existing_nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=2000),
               comment='日记内容，1-2000字符',
               existing_nullable=False)
        batch_op.alter_column('mood_tag',
               existing_type=postgresql.ENUM('HAPPY', 'CALM', 'SAD', 'ANGRY', 'TIRED', name='moodtype'),
               comment='情绪标签',
               existing_nullable=False)

    # ### end Alembic commands ###
