"""Initial migration

Revision ID: de707e93b7ec
Revises: 
Create Date: 2026-05-06 08:45:39.630888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de707e93b7ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_codes',
    sa.Column('phone', sa.String(length=11), nullable=False, comment='手机号'),
    sa.Column('code', sa.String(length=6), nullable=False, comment='6位验证码'),
    sa.Column('action', sa.String(length=20), nullable=False, comment='验证码用途：login/bind'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='过期时间'),
    sa.Column('used', sa.Boolean(), nullable=False, comment='是否已使用'),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sms_codes', schema=None) as batch_op:
        batch_op.create_index('idx_phone_action_expires', ['phone', 'action', 'expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_codes_phone'), ['phone'], unique=False)

    op.create_table('users',
    sa.Column('phone', sa.String(length=11), nullable=True, comment='手机号，唯一索引，可为空'),
    sa.Column('nickname', sa.String(length=20), nullable=False, comment='用户昵称，1-20字符，全局唯一'),
    sa.Column('avatar', sa.Text(), nullable=True, comment='头像URL或base64'),
    sa.Column('password_hash', sa.String(length=256), nullable=True, comment='密码哈希（bcrypt）'),
    sa.Column('wechat_openid', sa.String(length=128), nullable=True, comment='微信OpenID'),
    sa.Column('wechat_unionid', sa.String(length=128), nullable=True, comment='微信UnionID'),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('wechat_unionid')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_wechat_openid'), ['wechat_openid'], unique=True)

    op.create_table('answer_records',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('question', sa.String(length=200), nullable=False, comment='提问内容，1-200字符'),
    sa.Column('answer_text', sa.String(length=100), nullable=False, comment='答案内容，1-100字符'),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answer_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answer_records_user_id'), ['user_id'], unique=False)

    op.create_table('diary_entries',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('mood_tag', sa.Enum('HAPPY', 'CALM', 'SAD', 'ANGRY', 'TIRED', name='moodtype'), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diary_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diary_entries_created_date'), ['created_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_diary_entries_user_id'), ['user_id'], unique=False)

    op.create_table('fortune_records',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='运势所属日期'),
    sa.Column('score', sa.Integer(), nullable=False, comment='运势分数0-100'),
    sa.Column('title', sa.String(length=20), nullable=False, comment='运势标题，1-20字符'),
    sa.Column('content', sa.String(length=200), nullable=False, comment='运势内容，1-200字符'),
    sa.Column('yi', postgresql.ARRAY(sa.String(length=20)), nullable=False, comment='宜事项数组，最多5个'),
    sa.Column('ji', postgresql.ARRAY(sa.String(length=20)), nullable=False, comment='忌事项数组，最多5个'),
    sa.Column('lucky_color', sa.String(length=20), nullable=True, comment='幸运颜色'),
    sa.Column('lucky_direction', sa.String(length=20), nullable=True, comment='幸运方向'),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_date')
    )
    with op.batch_alter_table('fortune_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fortune_records_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fortune_records_user_id'), ['user_id'], unique=False)

    op.create_table('mood_analysis_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trigger_event', sa.String(length=32), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('result_text', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    with op.batch_alter_table('mood_analysis_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mood_analysis_jobs_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mood_analysis_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_mood_analysis_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('user_profiles',
    sa.Column('user_id', sa.String(length=64), nullable=False, comment='用户ID，主键'),
    sa.Column('answer_style', sa.Enum('PHILOSOPHICAL', 'HUMOR', name='answerstyle'), nullable=True, comment='用户偏好的答案风格：philosophical/humor'),
    sa.Column('topic_interests', postgresql.ARRAY(sa.String(length=20)), nullable=True, comment='兴趣标签数组，如 ["love","career","health"]'),
    sa.Column('self_context_tag', sa.String(length=64), nullable=True, comment='用户自述场景，如“考研期”'),
    sa.Column('mood_tendency', sa.String(length=50), nullable=True, comment='情绪倾向，AI分析生成，例如"optimistic"/"anxious"等'),
    sa.Column('preferred_feature', sa.Enum('MOOD_DIARY', 'FORTUNE', 'ANSWER', name='preferredfeature'), nullable=True, comment='最常用功能：mood_diary/fortune/answer'),
    sa.Column('active_hour_bucket', sa.Enum('MORNING', 'AFTERNOON', 'NIGHT', name='activehourbucket'), nullable=True, comment='活跃时段：morning/afternoon/night'),
    sa.Column('personalization_enabled', sa.Boolean(), nullable=False, comment='是否开启个性化推荐，默认true'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('favorites',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('answer_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answer_records.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'answer_id', name='uq_user_answer')
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorites_answer_id'), ['answer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorites_user_id'), ['user_id'], unique=False)

    op.create_table('plaza_cards',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('FORTUNE', 'ANSWER', name='cardtype'), nullable=False),
    sa.Column('snapshot_url', sa.String(length=500), nullable=False),
    sa.Column('content', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=10)), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('fortune_id', sa.String(length=64), nullable=True),
    sa.Column('answer_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(type = 'FORTUNE' AND fortune_id IS NOT NULL AND answer_id IS NULL) OR (type = 'ANSWER' AND answer_id IS NOT NULL AND fortune_id IS NULL)", name='check_valid_source'),
    sa.ForeignKeyConstraint(['answer_id'], ['answer_records.id'], ),
    sa.ForeignKeyConstraint(['fortune_id'], ['fortune_records.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plaza_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plaza_cards_user_id'), ['user_id'], unique=False)

    op.create_table('likes',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('card_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['plaza_cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'card_id', name='uq_user_card')
    )
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_likes_card_id'), ['card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_likes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_likes_user_id'))
        batch_op.drop_index(batch_op.f('ix_likes_card_id'))

    op.drop_table('likes')
    with op.batch_alter_table('plaza_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plaza_cards_user_id'))

    op.drop_table('plaza_cards')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorites_user_id'))
        batch_op.drop_index(batch_op.f('ix_favorites_answer_id'))

    op.drop_table('favorites')
    op.drop_table('user_profiles')
    with op.batch_alter_table('mood_analysis_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mood_analysis_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_mood_analysis_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_mood_analysis_jobs_next_run_at'))

    op.drop_table('mood_analysis_jobs')
    with op.batch_alter_table('fortune_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fortune_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_fortune_records_date'))

    op.drop_table('fortune_records')
    with op.batch_alter_table('diary_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diary_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_diary_entries_created_date'))

    op.drop_table('diary_entries')
    with op.batch_alter_table('answer_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answer_records_user_id'))

    op.drop_table('answer_records')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_wechat_openid'))
        batch_op.drop_index(batch_op.f('ix_users_phone'))

    op.drop_table('users')
    with op.batch_alter_table('sms_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_codes_phone'))
        batch_op.drop_index('idx_phone_action_expires')

    op.drop_table('sms_codes')
    # ### end Alembic commands ###
